# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='AdReviewRegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdReviewUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounterReviewRegisteredUser',
            fields=[
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='board.Ad')),
                ('counter', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounterReviewUser',
            fields=[
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='board.Ad')),
                ('counter', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adreviewuser',
            name='ad',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='board.Ad'),
        ),
        migrations.AddField(
            model_name='adreviewregistereduser',
            name='ad',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='board.Ad'),
        ),
        migrations.AddField(
            model_name='adreviewregistereduser',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='adreviewuser',
            unique_together=set([('ad', 'ip')]),
        ),
        migrations.AlterUniqueTogether(
            name='adreviewregistereduser',
            unique_together=set([('ad', 'user')]),
        ),
    ]
